//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Re-generate with: controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties of StartupBoostPolicy into out.
func (in *StartupBoostPolicy) DeepCopyInto(out *StartupBoostPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StartupBoostPolicy) DeepCopy() *StartupBoostPolicy {
	if in == nil {
		return nil
	}
	out := new(StartupBoostPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *StartupBoostPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of StartupBoostPolicyList into out.
func (in *StartupBoostPolicyList) DeepCopyInto(out *StartupBoostPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StartupBoostPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StartupBoostPolicyList) DeepCopy() *StartupBoostPolicyList {
	if in == nil {
		return nil
	}
	out := new(StartupBoostPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *StartupBoostPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of StartupBoostPolicySpec into out.
func (in *StartupBoostPolicySpec) DeepCopyInto(out *StartupBoostPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerBoostSpec, len(*in))
		copy(*out, *in)
	}
}

func (in *StartupBoostPolicySpec) DeepCopy() *StartupBoostPolicySpec {
	if in == nil {
		return nil
	}
	out := new(StartupBoostPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ContainerBoostSpec into out.
func (in *ContainerBoostSpec) DeepCopyInto(out *ContainerBoostSpec) {
	*out = *in
}

func (in *ContainerBoostSpec) DeepCopy() *ContainerBoostSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerBoostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of StartupBoostPolicyStatus into out.
func (in *StartupBoostPolicyStatus) DeepCopyInto(out *StartupBoostPolicyStatus) {
	*out = *in
	if in.BoostedPods != nil {
		in, out := &in.BoostedPods, &out.BoostedPods
		*out = make([]PodBoostStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StartupBoostPolicyStatus) DeepCopy() *StartupBoostPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(StartupBoostPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of PodBoostStatus into out.
func (in *PodBoostStatus) DeepCopyInto(out *PodBoostStatus) {
	*out = *in
	if in.ResizedAt != nil {
		in, out := &in.ResizedAt, &out.ResizedAt
		*out = (*in).DeepCopy()
	}
}

func (in *PodBoostStatus) DeepCopy() *PodBoostStatus {
	if in == nil {
		return nil
	}
	out := new(PodBoostStatus)
	in.DeepCopyInto(out)
	return out
}
